[package]
name = "bevy_proj"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.0"
bevy-inspector-egui = "0.23.2"
bevy_entitiles = "0.7.0"
serde ={ version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"

[profile.dev]
opt-level = 1

[profile.dev.packages."*"]
opt-level = 3

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"